#pragma once
enum WINMODE { WINMODE_FULL, WINMODE_WIN };
enum MOUSEBUTTON { DIM_LBUTTON, DIM_RBUTTON, DIM_WHEEL, DIM_XBUTTON };
enum MOUSEMOVE { DIM_X, DIM_Y, DIM_Z };
enum SCENEID { SCENE_STATIC, SCENE_END };
enum RENDERGROUP { RENDER_PRIORITY, RENDER_NONEALPHA, RENDER_ALPHA, RENDER_UI ,RENDER_EFFECT, RENDER_END };
enum STATE { STATE_RIGHT, STATE_UP, STATE_LOOK, STATE_POSITION, STATE_END };
enum TEXTURE_TYPE { TEXTURE_TYPE_GENERAL, TEXTURE_TYPE_CUBE, TEXTURE_TYPE_END };
enum POINT_ { POINT_A, POINT_B, POINT_C, POINT_END };
enum NEIGHBOR { NEIGHBOR_AB, NEIGHBOR_BC, NEIGHBOR_CA, NEIGHBOR_END };
enum LINE { LINE_AB, LINE_BC, LINE_CA, LINE_END };
enum TOOL_MODE { MODE_UNIT, MODE_EFFECT, MODE_UI, MODE_NAVIMESH, MODE_CAMERA, MODE_TERRAIN, MODE_END };
enum ANIMATE_PLAY { ANIMATE_PLAY_ONCE, ANIMATE_PLAY_ANY, ANIMATE_PLAY_END };
enum UI { UI_HP_BACK, UI_MP_BACK, UI_HP, UI_MP, UI_END };
enum COLLIDER_TYPE { COLLIDER_TYPE_SPHERE, COLLIDER_TYPE_BOX, COLLIDER_TYPE_END };
enum BOX_TYPE { BOX_TYPE_AABB, BOX_TYPE_OBB, BOX_TYPE_END };
enum NAVI {NAVI_PLAYER, NAVI_MONSTER, NAVI_NPC, NAVI_END};

enum NAVI_MODE {NAVI_MODE_CREATE, NAVI_MODE_MODIFY, NAVI_MODE_DELETE, NAVI_MODE_END};

enum MESH_TYPE {STATIC, DYNAMIC, NONE};
